"use client";
import {useEffect,useMemo,useState} from "react";
import {Menu,X,Moon,Sun,Sparkles,Wind,BookOpen,Clock3,NotebookPen,ShieldCheck,Save,Trash2,Mountain,Cloud,Flame,Leaf} from "lucide-react";
const nav=[['मुखपृष्ठ','home'],['स्वर ज्ञान','swara'],['नाड़ियाँ','nadi'],['प्राण','prana'],['पंचतत्त्व','tatva'],['होरा','hora'],['स्वर डायरी','diary'],['अभ्यास','learn'],['सावधानियाँ','safety']];
const swaras=[['चन्द्र स्वर','इड़ा • बायीं नासिका','शीतलता, शांति और ग्रहणशीलता से पारंपरिक संबंध।',Moon,'moon'],['सूर्य स्वर','पिंगला • दायीं नासिका','ऊष्मा, सक्रियता और बाह्य क्रिया से पारंपरिक संबंध।',Sun,'sun'],['सुषुम्ना स्वर','दोनों नासिकाओं में संतुलन','ध्यान, मौन और आध्यात्मिक अभ्यास से पारंपरिक संबंध।',Sparkles,'purple']] as const;
const nadis=[['इड़ा','बायीं नासिका से मूलाधार','शीतल, मानसिक प्रवाह'],['पिंगला','दायीं नासिका से मूलाधार','उष्ण, सक्रिय प्रवाह'],['सुषुम्ना','मेरुदंड का मध्य मार्ग','ध्यान व संतुलन'],['गांधारी','बायीं आँख','दृष्टि का संबंध'],['हस्तिजिह्वा','दायीं आँख','दृष्टि का संबंध'],['पूषा','दायाँ कान','श्रवण से संबंध'],['यशस्विनी','बायाँ कान','श्रवण से संबंध'],['अलम्बुषा','मुख से गुदा क्षेत्र','आहार प्रवाह'],['कुहू','जनन क्षेत्र','उत्सर्जन व प्रजनन'],['शंखिनी','कंठ व जनन क्षेत्र','द्रव निष्कासन']];
const pranas=[['प्राण','हृदय व वक्ष','श्वसन और ग्रहण'],['अपान','नाभि के नीचे','उत्सर्जन'],['समान','नाभि क्षेत्र','पाचन व आत्मसात'],['उदान','कंठ व सिर','वाणी व ऊर्ध्व प्रवाह'],['व्यान','समस्त शरीर','संचरण व समन्वय'],['नाग','उदर','डकार'],['कूर्म','नेत्र','पलक झपकना'],['कृकल','कंठ','छींक व भूख'],['देवदत्त','मुख','जम्हाई व निद्रा'],['धनंजय','समस्त शरीर','स्थायी प्रवाह']];
const planets=[['सूर्य','नेतृत्व'],['शुक्र','कला व संबंध'],['बुध','अध्ययन व वाणी'],['चन्द्र','मन व संवेदना'],['शनि','अनुशासन'],['बृहस्पति','ज्ञान व विस्तार'],['मंगल','साहस व सक्रियता']];
type Entry={id:number,date:string,time:string,swara:string,mood:string,energy:number,activity:string,notes:string};
export default function Portal(){const [menu,setMenu]=useState(false),[flow,setFlow]=useState('');const now=new Date();const [hora,setHora]=useState({date:now.toISOString().slice(0,10),sunrise:'06:00',current:now.toTimeString().slice(0,5)});const blank={date:now.toISOString().slice(0,10),time:now.toTimeString().slice(0,5),swara:'चन्द्र',mood:'शांत',energy:3,activity:'',notes:''};const [form,setForm]=useState(blank);const [entries,setEntries]=useState<Entry[]>([]);
useEffect(()=>{try{setEntries(JSON.parse(localStorage.getItem('swara-diary')||'[]'))}catch{}},[]);const store=(x:Entry[])=>{setEntries(x);localStorage.setItem('swara-diary',JSON.stringify(x))};
const hd=useMemo(()=>{const dayStart=[0,3,2,6,1,5,4][new Date(hora.date+'T00:00').getDay()];const [sh,sm]=hora.sunrise.split(':').map(Number),[ch,cm]=hora.current.split(':').map(Number);let m=ch*60+cm-sh*60-sm;if(m<0)m+=1440;const active=Math.floor(m/60);return {active,items:Array.from({length:24},(_,i)=>{const p=planets[(dayStart+i)%7],t=(sh*60+sm+i*60)%1440;return {p,time:`${String(Math.floor(t/60)).padStart(2,'0')}:${String(t%60).padStart(2,'0')}`}})}} ,[hora]);
return <><header><a className="brand" href="#home"><b>ॐ</b><span>शिव स्वरोदय<small>ज्ञानकोष</small></span></a><nav>{nav.map(n=><a key={n[1]} href={'#'+n[1]}>{n[0]}</a>)}</nav><button aria-label="मेन्यू" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>{menu&&<aside>{nav.map(n=><a onClick={()=>setMenu(false)} key={n[1]} href={'#'+n[1]}>{n[0]}</a>)}</aside>}<main>
<section id="home" className="hero"><div><span className="tag">✦ प्राचीन विद्या • सहज अध्ययन</span><h1>शिव स्वरोदय<br/><em>ज्ञानकोष</em></h1><p>श्वास, स्वर, नाड़ी, प्राण और पंचतत्त्व का पारंपरिक अध्ययन</p><div className="actions"><a className="btn primary" href="#swara">अध्ययन प्रारम्भ करें →</a><a className="btn ghost" href="#identify">वर्तमान स्वर पहचानें</a></div><div className="stats"><span>१० नाड़ियाँ</span><span>१० प्राण</span><span>५ तत्त्व</span></div></div><div className="cosmos"><i/><i/><strong>ॐ</strong><Moon/><Sun/></div></section>
<section className="intro"><div><small>स्वर का विज्ञान</small><h2>श्वास में छिपी लय को देखें</h2></div><p>शिव स्वरोदय भारतीय योग परंपरा में श्वास के प्रवाह का अवलोकन है। यहाँ मान्यताओं को सरल और जिम्मेदार शैक्षिक रूप में प्रस्तुत किया गया है—बिना चिकित्सकीय दावे के।</p></section>
<Section id="swara" icon={<Wind/>} tag="स्वर ज्ञान" title="तीन प्रमुख स्वर" sub="हर स्वर को परंपरा में विशिष्ट गुण और ऊर्जा से जोड़ा गया है।"><div className="grid three">{swaras.map(([n,s,t,I,c])=><article className={'swara '+c} key={n}><I/><small>{s}</small><h3>{n}</h3><p>{t}</p></article>)}</div></Section>
<section id="identify" className="identify"><div><small>इंटरैक्टिव अभ्यास</small><h2>अपना वर्तमान स्वर पहचानें</h2><ol><li><b>१</b> सहज होकर बैठें और सामान्य श्वास लें।</li><li><b>२</b> हथेली नाक के नीचे रखकर प्रवाह देखें।</li><li><b>३</b> अपना अनुभव चुनें।</li></ol></div><div className="tool">{[['left','बायीं नासिका से अधिक'],['right','दायीं नासिका से अधिक'],['both','दोनों से लगभग समान']].map(x=><button className={flow===x[0]?'selected':''} onClick={()=>setFlow(x[0])} key={x[0]}>{x[1]}</button>)}{flow&&<div className="result"><Sparkles/><div><small>आपका वर्तमान स्वर</small><h3>{flow==='left'?'चन्द्र / इड़ा':flow==='right'?'सूर्य / पिंगला':'सुषुम्ना'}</h3><p>{flow==='both'?'दोनों नासिकाओं में लगभग संतुलित प्रवाह।':'एक नासिका में अधिक अनुभव किया गया प्रवाह।'}</p></div></div>}<button disabled={!flow} className="btn primary" onClick={()=>localStorage.setItem('last-swara',JSON.stringify({flow,at:new Date()}))}><Save/> अवलोकन सुरक्षित करें</button></div></section>
<Section dark id="nadi" icon={<Leaf/>} tag="सूक्ष्म ऊर्जा मार्ग" title="दस प्रमुख नाड़ियाँ" sub="पारंपरिक स्थान और आरोपित कार्य।"><div className="nadiGrid">{nadis.map((n,i)=><article key={n[0]}><b>{String(i+1).padStart(2,'0')}</b><div><h3>{n[0]}</h3><p>{n[1]}</p><small>{n[2]}</small></div></article>)}</div></Section>
<Section id="prana" icon={<Wind/>} tag="जीवन वायु" title="दस प्राण" sub="पाँच मुख्य और पाँच उप-प्राणों का पारंपरिक परिचय।"><h3 className="group">पंच प्रमुख प्राण</h3><div className="grid five">{pranas.slice(0,5).map(Card)}</div><h3 className="group">पंच उप-प्राण</h3><div className="grid five">{pranas.slice(5).map(Card)}</div></Section>
<Section id="tatva" icon={<Sparkles/>} tag="तत्त्व चक्र" title="पंचतत्त्व" sub="ये पारंपरिक विवरण हैं; वैज्ञानिक रूप से सत्यापित तथ्य नहीं।"><div className="grid five">{[['पृथ्वी','लं','पीला','20',Mountain],['जल','वं','श्वेत','16',Cloud],['अग्नि','रं','लाल','12',Flame],['वायु','यं','नीला/हरा','8',Wind],['आकाश','हं','गहरा नीला','4',Sparkles]].map(([n,b,c,d,I])=>{const Icon=I as typeof Sun;return <article className="tatva" key={n as string}><Icon/><small>बीज मंत्र</small><strong>{b as string}</strong><h3>{n as string}</h3><p>{c as string}</p><span>{d as string} मिनट</span></article>})}</div></Section>
<Section id="hora" icon={<Clock3/>} tag="शैक्षिक गणना" title="होरा कैलकुलेटर" sub="सात ग्रहों के दोहराते क्रम पर आधारित सरल गणना।"><div className="hora"><div className="form"><label>दिनांक<input type="date" value={hora.date} onChange={e=>setHora({...hora,date:e.target.value})}/></label><label>सूर्योदय<input type="time" value={hora.sunrise} onChange={e=>setHora({...hora,sunrise:e.target.value})}/></label><label>वर्तमान समय<input type="time" value={hora.current} onChange={e=>setHora({...hora,current:e.target.value})}/></label><div className="current"><Sun/><small>वर्तमान होरा</small><h2>{hd.items[hd.active].p[0]}</h2><p>{hd.items[hd.active].p[1]}</p></div><p className="note">यह समान 60-मिनट खंडों पर आधारित सरलीकृत शैक्षिक कैलकुलेटर है।</p></div><div className="timeline">{hd.items.map((x,i)=><div className={i===hd.active?'active':''} key={i}><b>{i+1}</b><span>{x.time}</span><strong>{x.p[0]}</strong><small>{x.p[1]}</small></div>)}</div></div></Section>
<Section id="diary" icon={<NotebookPen/>} tag="निजी अवलोकन" title="दैनिक स्वर डायरी" sub="रिकॉर्ड केवल इसी ब्राउज़र में सुरक्षित रहते हैं।"><div className="diary"><form onSubmit={e=>{e.preventDefault();store([{...form,id:Date.now()},...entries]);setForm(blank)}}><div className="formGrid"><label>दिनांक<input required type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>समय<input required type="time" value={form.time} onChange={e=>setForm({...form,time:e.target.value})}/></label><label>स्वर<select value={form.swara} onChange={e=>setForm({...form,swara:e.target.value})}><option>चन्द्र</option><option>सूर्य</option><option>सुषुम्ना</option></select></label><label>मनोभाव<input value={form.mood} onChange={e=>setForm({...form,mood:e.target.value})}/></label><label>ऊर्जा {form.energy}/5<input type="range" min="1" max="5" value={form.energy} onChange={e=>setForm({...form,energy:+e.target.value})}/></label><label>गतिविधि<input value={form.activity} onChange={e=>setForm({...form,activity:e.target.value})}/></label></div><label>टिप्पणी<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="btn primary"><Save/> डायरी में जोड़ें</button></form><div className="entries"><div className="summary"><b>{entries.filter(d=>Date.now()-new Date(d.date).getTime()<604800000).length}</b><span>पिछले 7 दिनों के अवलोकन</span></div>{entries.map(d=><article key={d.id}><div><small>{d.date} • {d.time}</small><h3>{d.swara} स्वर</h3><p>{d.mood} • ऊर्जा {d.energy}/5 • {d.activity}</p><blockquote>{d.notes}</blockquote></div><button aria-label="हटाएँ" onClick={()=>store(entries.filter(x=>x.id!==d.id))}><Trash2/></button></article>)}</div></div></Section>
<Section id="learn" icon={<BookOpen/>} tag="क्रमिक अध्ययन" title="अपनी गति से सीखें" sub="अवलोकन से आरम्भ करें; उन्नत अभ्यास योग्य शिक्षक के मार्गदर्शन में करें।"><div className="levels">{[['01','प्राकृतिक श्वास का अवलोकन'],['02','इड़ा, पिंगला, सुषुम्ना, प्राण और पंचतत्त्व'],['03','योग्य शिक्षक के मार्गदर्शन में उन्नत अभ्यास']].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[0]==='03'?'श्वास-नियंत्रण या उन्नत साधना अकेले न करें।':'अध्ययन और सहज अवलोकन से अपनी समझ विकसित करें।'}</p></article>)}</div></Section>
<section id="safety" className="safety"><ShieldCheck/><div><small>सुरक्षा सर्वप्रथम</small><h2>महत्वपूर्ण सावधानी</h2><p>यह वेबसाइट शिव स्वरोदय की पारंपरिक एवं आध्यात्मिक मान्यताओं का शैक्षणिक प्रस्तुतीकरण है। यह वैज्ञानिक चिकित्सा-जाँच, रोग-निदान, गर्भनिरोध या उपचार का विकल्प नहीं है। स्वास्थ्य या गर्भावस्था से संबंधित निर्णय के लिए योग्य चिकित्सक की सलाह लें।</p><ul><li>कोई रोग-निदान या उपचार अनुशंसा नहीं</li><li>कोई गर्भावस्था या भ्रूण-लिंग भविष्यवाणी नहीं</li><li>कोई निश्चित भविष्यवाणी या परिणाम की गारंटी नहीं</li></ul></div></section></main><footer><div className="brand"><b>ॐ</b><span>शिव स्वरोदय<small>ज्ञानकोष</small></span></div><p>परंपरा का सम्मान • ज्ञान की स्पष्टता • अभ्यास में सावधानी</p><a href="#home">ऊपर जाएँ ↑</a></footer></>}
function Section({id,icon,tag,title,sub,children,dark=false}:{id:string,icon:React.ReactNode,tag:string,title:string,sub:string,children:React.ReactNode,dark?:boolean}){return <section id={id} className={'section '+(dark?'dark':'')}><div className="heading"><span>{icon}</span><div><small>{tag}</small><h2>{title}</h2><p>{sub}</p></div></div>{children}</section>}
function Card(p:string[]){return <article className="info" key={p[0]}><b>{p[0][0]}</b><div><h3>{p[0]}</h3><small>{p[1]}</small><p>{p[2]}</p></div></article>}
